[package]
name = "retrofw2-rust"
version = "0.1.0"
authors = ["alex <alex@pdp7.net>"]
edition = "2018"

[dependencies]
sdl = "0.3.6"
ao_rs = { git = "https://github.com/alexpdp7/ao-rs", branch = "update" }
rand = { version = "0.7.3" , features = ["small_rng"] }